#!/bin/bash

# Kubernetes 프로덕션 환경 설정 파일
# 작성일: 2025년 8월 3일

# 기본 설정
CLUSTER_NAME="${CLUSTER_NAME:-production}"
NAMESPACE_PREFIX="${NAMESPACE_PREFIX:-prod}"
ARGOCD_VERSION="${ARGOCD_VERSION:-v2.8.4}"
DOMAIN="${DOMAIN:-example.com}"
KUBECTL_VERSION="${KUBECTL_VERSION:-stable}"
HELM_VERSION="${HELM_VERSION:-v3.12.3}"
TERRAFORM_VERSION="${TERRAFORM_VERSION:-1.5.7}"

# 환경별 설정
PRODUCTION_NAMESPACE="production"
STAGING_NAMESPACE="staging"
ARGOCD_NAMESPACE="argocd"
MONITORING_NAMESPACE="monitoring"
INGRESS_NAMESPACE="ingress-nginx"
CERT_MANAGER_NAMESPACE="cert-manager"

# 리소스 제한
PROD_CPU_LIMIT="100"
PROD_MEMORY_LIMIT="200Gi"
STAGING_CPU_LIMIT="40"
STAGING_MEMORY_LIMIT="80Gi"

# 보안 설정
POD_SECURITY_STANDARD="restricted"
ENABLE_NETWORK_POLICIES="true"
ENABLE_RBAC="true"

# ArgoCD 설정
ARGOCD_HA_MODE="true"
ARGOCD_INGRESS_ENABLED="true"
ARGOCD_TLS_ENABLED="true"

# 모니터링 설정
PROMETHEUS_ENABLED="true"
GRAFANA_ENABLED="true"
ALERT_MANAGER_ENABLED="true"

# 플래그
DRY_RUN="${DRY_RUN:-false}"
VERBOSE="${VERBOSE:-false}"
DEBUG="${DEBUG:-false}"
